### ISSUE TITLE
Add instructions for download of CSV

### ISSUE THREAD

**Issue by larnsce** [openwashdata/glaas#2]
Hey @massarin, I am going through your README, please adapt the following

- [x] Add information on how to download the CSV

Alternatively, you can download the individual datasets as a CSV or XLSX file from the table below.

- Click Download CSV. A window opens that displays the CSV in your browser.
- Right-click anywhere inside the window and select “Save Page As…”.
- Save the file in a folder of your choice.

Taken from: https://openwashdata.github.io/ploswater/

This should also become the standard for `washr` and `fairenough`

I noticed you removed the XLSX download. I am inclined to do the same for the future, hoping that people will learn to open a CSV in MS Excel and go from there.

**Comment by massarin** [comment]
I think the best way to do this is to add a workflow that will add the csvs as assets, e.g.

https://github.com/softprops/action-gh-release?tab=readme-ov-file#%EF%B8%8F-uploading-release-assets

add something like

```
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: inst/extdata/glaas.csv
```

the complete list of files can be generated by a script.

Then this way, since they will be release assets, github will automatically generate a download link, which we can link in the readme.
